# Generated by Django 4.2.2 on 2023-06-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('imagen', models.CharField(max_length=500, verbose_name='Imagen')),
                ('stock', models.IntegerField(verbose_name='Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=200)),
                ('contraseña', models.CharField(max_length=12)),
            ],
        ),
    ]
