# Generated by Django 4.2.2 on 2023-06-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=12, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña2',
            field=models.CharField(max_length=12, verbose_name='Contraseña 2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=200, verbose_name='Correo'),
        ),
    ]
